site_name: Documentation MDMY GROUP
site_description: Centre de documentation technique et commerciale
site_url: https://www.mdmygroup.com/docs/

# Repository
repo_name: mdmy-mkdocs
repo_url: https://github.com/mdmy-group/mdmy-mkdocs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2024-2025 MDMY GROUP SAS

# Theme configuration
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Passer au mode sombre
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Passer au mode clair
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Plugins
plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: 'Imprimer la Documentation'
  - minify:
      minify_html: true

# Extra CSS for custom styling
extra_stylesheets:
  - assets/stylesheets/extra.css

# Navigation structure
nav:
  - Accueil: index.md
  - Démarrage: getting-started.md
  - Services:
    - services/index.md
    - Web Design: services/web-design.md
    - Stratégie Digitale: services/digital-strategy.md
    - E-Commerce: services/e-commerce.md
    - Hébergement & Support: services/hosting-support.md
  - Guides:
    - guides/index.md
    - Guide 1: guides/guide-1.md
    - Guide 2: guides/guide-2.md
  - Référence:
    - reference/index.md
    - API: reference/api-reference.md
  - À Propos: about.md
  - Contact: contact.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdmy-group
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mdmygroup
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/mdmygroup
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
    default: latest
  consent:
    title: Consentement aux cookies
    description: >-
      Nous utilisons des cookies pour reconnaître vos visites répétées et vos préférences, ainsi que 
      pour mesurer l'efficacité de notre documentation et déterminer si les utilisateurs 
      trouvent ce qu'ils recherchent.