site_name: MDMY Documentation
site_description: Technical and business documentation hub
site_url: https://example.com/

# Repository
repo_name: mdmy-mkdocs
repo_url: https://github.com/mdmy-group/mdmy-mkdocs
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 MDMY Group

# Theme configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  logo: assets/logo.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

# Plugins
plugins:
  - search
  - print-site:
      add_to_navigation: true
      print_page_title: 'Print Documentation'
  - minify:
      minify_html: true

# Extra CSS for custom styling
extra_stylesheets:
  - assets/stylesheets/extra.css

# Navigation structure
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Guides:
    - guides/index.md
    - Guide 1: guides/guide-1.md
    - Guide 2: guides/guide-2.md
  - Reference:
    - reference/index.md
    - API Reference: reference/api-reference.md
  - About: about.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mdmy-group
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mdmygroup
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  version:
    provider: mike
    default: latest
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for.